### ISSUE TITLE
mqtt

### ISSUE THREAD

**Issue by 3skelion** [maxmostovoy/vakio-public-api#1]
Вопрос по mqtt!

Как мне узнать статус устройства? Я отправляю команды через топики vakio/mode  (Команда = 06021 ) Прибор включит режим приток, но как узнать включено ли устройство и  какая скорость ?????

Vakio Base Smart

**Comment by SergeyKupavtsev** [comment]
Здравствуйте, прибор изменения режимов так-же отправляет на vakio/mode. Формат команд такой же, как в описании. Поэтому, чтобы получать изменения нужно быть подписанным на vakio/mode.

**Comment by AlexBokhankovich** [comment]
> Здравствуйте, прибор изменения режимов так-же отправляет на vakio/mode. Формат команд такой же, как в описании. Поэтому, чтобы получать изменения нужно быть подписанным на vakio/mode.

Нет, это СОВСЕМ не то, что нужно.

Я так понимаю, автор, ровно как и я, хотел бы получать текущий статус девайса. Например, вот прям сейчас я подключился к рекуператору и вижу в mode 06507. 
Что мне это должно дать?
Какой включен режим?
До тех пор, пока я сам не натыкаю в нем режимы, я не знаю какой текущий. Я. вижу только последнюю отданную команду. Принцип похож через тупое управление по ИК каналу. Обратной связи нет.

По-хорошему, надо сделать всего 3 топика: режим, скорость вентилятора и состояние вкл\выкл (можно и в режим завести). Всё, все проблемы будут решены.
Текущий режим с командами не позволяет интегрировать рекуператор в более-менее адекватном виде в систему умного дома. MQTT протокол здесь реализован максимально коряво и неправильно, специально даже не придумаешь такое.

посмотрите ради интереса как реализован MQTT в Haier: https://sprut.ai/article/podklyuchenie-kondicionerov-haier-k-home-assistant

В текущем виде Base Smart для умного дома не более, чем игрушка, а MQTT - просто модная аббревиатура на коробке. Откройте исходники, дайте возможность допилить самим пользователям

**Comment by SergeyKupavtsev** [comment]
> > Здравствуйте, прибор изменения режимов так-же отправляет на vakio/mode. Формат команды такой же, как в описании. Поэтому для получения изменений необходимо быть подписанным на vakio/mode.
> 
> Нет, это СОВСЕМ не то, что нужно.
> 
> Я так понимаю, автор, прямо как и я хотел бы получить статус устройства. Например, вот прямо сейчас я подключился к рекуператору и вижу в режиме 06507. Что мне это должно было дать? Какой включен режим? До тех пор, пока я сам не натыкаю в нем режимы, я не знаю, какую работу. Я вижу только последнюю отданную команду. похоже на тупое Принцип управления по ИК каналу. Обратной связи нет.
> 
> По-хорошему, надо сделать всего 3 темы: режим, скорость вентилятора и состояние вкл\выкл (можно и в режиме завести). Всё, все проблемы будут решены. Текущий режим с командами не позволяет интегрировать рекуператор в менее адекватном виде в системе умного дома. Протокол MQTT здесь реализуется максимально коряво неправильно, особенно даже не придумывая такое.
> 
> ради интереса как реализуется MQTT в Haier: https://sprut.ai/article/podklyuchenie-kondicionerov-haier-k-home-assistant
> 
> В предполагаемом виде Base Smart для умного дома не более, игрушка чем, а MQTT - просто модная аббревиатура на коробке. Откройте исходники, дайте возможность допилить самих пользователей
> 
> UPD: в соседней жижу вижу, что в openair уже что-то более вменяемое реализуется в планетарной безопасности. Обновите плз у смарт прошивку тоже

У нас более сложная структура работы всей системы, MQTT используется только для обмена сообщениями, для других целей он не рассматривается. Для хранения актуальной информации о приборе используется база данных. В своих умных домах, если требуется хранение актуальной информации, нужно использовать дополнительные ресурсы.

**Comment by AlexBokhankovich** [comment]
> В своих умных домах, если требуется хранение актуальной информации, нужно использовать дополнительные ресурсы.

НУ вы должны осознавать, что 95% "умных" домов реализуются на готовых  решениях типа HomeAssistant, Sprut.hub и тд. и ни в одно их этих решений не интегрируется, как интегрируются другие устройства с нормальной реализацией протокола. Я понимаю, что можно написать поверх вашей реализации что-то более вменяемое и хранить в нем состояния, но это будет еще один дополнительный сервис, берущий на себя практически всю логику, а не простой мапинг в конфиг файлах, как это должно быть при нормальной реализации. Я более чем уверен, что никто этим заниматься не будет.
В чем сложность реализовать, раз так нужно, двойной подход: для своих целей вы так и оставляете общение через топик mode и команды, а интеграторам даёте "нормальный" MQTT, тем более что в openair это уже плюс минус сделано. Это же не ядерная физика - допилить прошивку рекуператора до поддержки адекватного протокола, тем более с учетом того, что оно уже реализовано в одной из железяк.

**Comment by AlexBokhankovich** [comment]
Здравствуйте. Новости есть по этой теме?

**Comment by xaos443** [comment]
Разработчики молчат, делать не хотят. по телефону не понимают что от них хотят.

**Comment by SergeyKupavtsev** [comment]
> Здравствуйте. Новости есть по этой теме?

Подготовил версию Base Smart с дополнительной работой по 3 топикам:
vakio/workmode
vakio/speed
vakio/state 
Завтра самостоятельно опробую дополнительно и выложу. Как обновить прибор и описание команд напишу так же завтра.

**Comment by SergeyKupavtsev** [comment]
> Здравствуйте. Новости есть по этой теме?

Вам нужно обновить прибор, для этого нужно отправить на топик  "Ваш топик"/system (По умолчанию, vakio/system) 
команду '0609' (Без ковычек). Прибор должен иметь доступ в интернет. После получения команды прибор начнет обновляться на более новую версию (1.1.4). Прошу  написать получилось или нет. 
По поводу общения с прибором 
vakio/state -> Работает с командами on/off 
vakio/speed -> скорость 1-7 
vakio/mode -> Режим работы 
inflow
recuperator
inflow_max
winter
outflow
outflow_max
night

**Comment by AlexBokhankovich** [comment]
> Вам нужно обновить прибор, для этого нужно отправить на топик "Ваш топик"/system (По умолчанию, vakio/system)
> команду '0609' (Без ковычек). Прибор должен иметь доступ в интернет. После получения команды прибор начнет обновляться на более новую версию (1.1.4). Прошу написать получилось или нет.

Получилось! Спасибо огромное! В работе еще не проверял, в ближайшее время опробую, отпишусь!
![image](https://user-images.githubusercontent.com/3011471/200292766-e95ad481-bc92-416a-af65-58b0b85af360.png)

**Comment by SergeyKupavtsev** [comment]
> > Вам нужно обновить прибор, для этого нужно отправить на топик "Ваш топик"/system (По умолчанию, vakio/system)
> > команду '0609' (Без ковычек). Прибор должен иметь доступ в интернет. После получения команды прибор начнет обновляться на более новую версию (1.1.4). Прошу написать получилось или нет.
> 
> Получилось! Спасибо огромное! В работе еще не проверял, в ближайшее время опробую, отпишусь! ![image](https://user-images.githubusercontent.com/3011471/200292766-e95ad481-bc92-416a-af65-58b0b85af360.png)

Спасибо за обратную связь!
