### ISSUE TITLE
управление openair mqtt

### ISSUE THREAD

**Issue by airens** [maxmostovoy/vakio-public-api#2]
Здравствуйте, почему-то прибор не реагирует на команды в топик vakio/mode. Посылаю, например 05505 согласно инструкции, чтобы установить скорость скорость 5, но никакой реакции. То же касается команд 0500* и 0513*. Что я делаю не так?
![изображение](https://user-images.githubusercontent.com/45446974/180380961-078157cd-d89e-42dd-9f49-f5d9d98bb5f2.png)

**Comment by SergeyKupavtsev** [comment]
У Вас новая версия прибора, формат общения по json. Дополнили описание.

**Comment by airens** [comment]
Вы пишете в инструкции, что регистрация посылается на:

> device/user_id/device_id/openair/system

Посмотрите на скриншот выше, где я должен взять `user_id`? По факту прибор шлет не то, что вы говорите

**Comment by SergeyKupavtsev** [comment]
При указании своего брокера mqtt, user_id/device_id меняется на имя топика указанного в настройках прибора. Допишу это в описании. (По умолчанию топик vakio) 
Пример, 
Топик - server/vakio/openair/mode
Сообщение 
{
"capabilities": 
    [
      {"speed": 2}
    ]
}
Выключить прибор. 
Топик тот же
Сообщение 
{
  "capabilities": 
     [
      {"on_off": "off"}
     ]
}

**Comment by airens** [comment]
Спасибо, все получилось. Нужно только было `"mode": "manual"` подать сначала
