### ISSUE TITLE
openair не обновляет выходные значения после команды MQTT

### ISSUE THREAD

**Issue by airens** [maxmostovoy/vakio-public-api#5]
Здравствуйте, прибор управляется по MQTT через топик, `server/vakio/openair/mode` нормально, но проблема в том, что он не выдает новое установленное значение в `device/vakio/openair/mode`. Этот топик обновляется только при управлении с кнопок. Есть способ это исправить?

**Comment by SergeyKupavtsev** [comment]
Здравствуйте, если я правильно понял, Вы хотите из топика получать актуальную информацию о режиме. В целом, топики используются только для обмена данными, для хранения актуальной информации, нужно использовать дополнительные ресурсы. Например, сохранять в базу данных.

**Comment by airens** [comment]
Хорошо, я послал команду, а прибор был в этот момент не доступен. В моей "базе" хранится значение, которое я подавал, но оно не отображает текущее состояние прибора и я даже не могу быть уверен, что прибор открыл заслонку! Кроме того, я заплатил больше 20т.р. за вентилятор с ESP и мне непонятно, с какой стати я должен ещё поднимать базу данных и писать специальную программу, чтобы этим прибором пользоваться в своём умном доме. Странная политика. В моей системе множество приборов, в том числе и MQTT и у всех основной функционал это топик, который отображает ТЕКУЩЕЕ состояние прибора и его статус

**Comment by xaos443** [comment]
Тоже не хватает данного функционала.

**Comment by SergeyKupavtsev** [comment]
До четверга подготовлю версию для OpenAira с обменом, как в ответе на https://github.com/maxmostovoy/vakio-public-api/issues/1

**Comment by SergeyKupavtsev** [comment]
> Тоже не хватает данного функционала.

Подготовил версию для Вашего Base Smart, завтра выложу и можно обновить прибор и будет работать общение по топикам /state /speed /workmode как в #1

**Comment by xaos443** [comment]
спасибо, жду. Рекуператор пока добавлен в приложение vakio. возможно сможете обновить?

**Comment by SergeyKupavtsev** [comment]
По поводу обновления OpenAir (Версии с 1.0.0X). Для обновления прибора нужно отправить на топик
server/Ваш топик/openair/system
Команду {"firmware":[{"start":1}]}
В случае неудачи, нужно подключить прибор в приложении, мы попробуем сделать это самостоятельно.

Сейчас сделал новую версию прибора с поддержкой топиков

топик/gate (1-4)
топик/speed (1-5)
топик/state (on/off)
топик/workmode (manual/super_auto)

В случае проблему можно писать на почту app@vakio.ru.
Спасибо за обратную связь!
