### ISSUE TITLE
Зависания при обработке MQTT команд

### ISSUE THREAD

**Issue by SergeyKupavtsev** [maxmostovoy/vakio-public-api#8]
> Здравствуйте, по поводу топиков, значение команд можно найти на https://vakio.ru/vakio-mqtt.pdf , в этом репозитории. По поводу команд speed, workmode, system на данный момент это новое обновление, поэтому, после массового обновления устройств, эти команды будут добавлены в данный репозиторий. @monoflash, по поводу зависаний, было бы хорошо, если Вы сможете описать подробнее проблему с зависанием (почта [app@vakio.ru](mailto:app@vakio.ru)), о такой проблемы на данный момент не было обращений и у нас она не возникала, поэтому Ваша обратная связь поможет улучшить продукт.

Добрый вечер, зависание было дважды, я не выяснял причины, но оно возникало всегда если отправлять более двух команд в MQTT быстро (без задержки). Возможности как либо отдебажить и посмотреть логи того что происходит внутри ESP32 в вентиляции у меня нет, поэтому это всё что могу сказать.

В документе что я опубликовал у себя есть системные команды **(которых нет в вашей документации)**, так что я командой обновления обновляю прошивку вентиляции и скорее всего позже допишу кнопочку для интеграции Home Assistant для обновления прошивки.

Если вы являетесь официальным представителем Vakio, было бы хорошо если бы вы опубликовали системные команды, они точно есть. Например команду полного сброса я нашёл через эксперименты, было сюрпризом что всё сбросить так просто...
А вообще, хотелось бы ещё:
1. Иметь возможность получить версию прошивки из вентиляции
2. Иметь возможность получить текущую версию прошивки у вас на сервере

Это всё нужно чтобы из интеграции или из собственного сервера выполнить команду обновления прошивки или отобразить уведомление в home assistant о возможности обновления прошивки.

Например такое есть в интеграции для Mikrotik RouterOS, очень полезно и удобно!

_Originally posted by @monoflash in https://github.com/maxmostovoy/vakio-public-api/issues/7#issuecomment-1398780257_

**Comment by SergeyKupavtsev** [comment]
Зависания отдебажу и будет исправлено.
По поводу новых команд, нет проблем, добавлю в новую версию эту возможность, так же обновлю документацию в этом репозитории, добавлю информацию о системных командах

**Comment by monoflash** [comment]
Как я писал в другой ветке, я сделал свой сервер который постоянно пингует вентиляцию по её IP который фиксированный. Через интеграцию с Home Assistant состояние вентиляции накопилось в виде графика.
По графику видно что вентиляция постоянно куда-то пропадает, либо теряет WiFi либо просто не отвечает на пинги. Сервер делает 4 пинга за раз каждые 30 секунд, так что это действительно реальный график доступности вентиляции в сети. [Код выполняющий пинги тут](https://github.com/monoflash/vakio/blob/master/server/server_message.go#L16-L70)
![График доступности](https://cdn.webdesk.ru/4f8c2db3a5f73f23e490100d77b2b3f6267e43f56857e33a7e984a2f45f2246affcbdecc61cbe0beb0fc849c2fb5ee03c896d3e6b8dd015f499888ee56b68ffe.png)

Какой-либо системы и периодичности не отслеживается... По крайней мере я не вижу.

**Comment by SergeyKupavtsev** [comment]
По поводу данной проблемы. Документацию актуализировал, все доступные команды пользователю описаны. По поводу зависания дисплея, проведя серию тестов с Vakio Base Smart, мы не смогли обнаружить зависания, но мы хотим решить данную проблему, для этого напишите нам на почту developer@vakio.ru , для скорейшего разрешения ситуации.
